name: conway
version: 1.0.0
description: >-
  Library that simulates Conway's Game of Life with multiple players.
  The last player with living cells wins the game.
dev_dependencies:
  test: ^1.15.3

